/**
 * 提交服务 — 处理 Fork → Branch → Commit → Push → Draft PR 流程。
 *
 * 不依赖终端交互，通过 onEvent 回调推送进度。
 * 包含失败恢复和本地回滚逻辑。
 */
import { v4 as uuid } from "uuid";
import { writeFile } from "node:fs/promises";
import { join, basename } from "node:path";
import type { Logger } from "../utils/log.js";
import type { PlatformAdapter, PlatformType } from "../platform/index.js";
import type { RepoMeta, FileContent } from "../types/facts.js";
import type { SubmitRecoveryInfo } from "../types/run.js";
import type { PipelineEventHandler } from "../pipeline/pipeline.js";
import {
  addForkRemote,
  removeForkRemote,
  createBranch,
  currentBranch,
  defaultBranch,
  stageFile,
  commit,
  pushBranch,
  execGit,
} from "../pr/git.js";
import { savePrRecord } from "../store/runs.js";

// ── 类型 ──

export interface SubmitInput {
  runId: string;
  tempDir: string;
  platform: PlatformType;
  adapter: PlatformAdapter;
  cloneResult: { tempDir: string; meta: RepoMeta };
  filteredReadme: string;
  generatedChineseReadme?: string;
  files: FileContent[];
  log: Logger;
  onEvent?: PipelineEventHandler;
}

export interface SubmitResult {
  success: boolean;
  prUrl?: string;
  prRecordId?: string;
  recoveryInfo?: SubmitRecoveryInfo;
  error?: string;
  partialFailure: boolean;
}

// ── 提交流程 ──

export async function submitChanges(input: SubmitInput): Promise<SubmitResult> {
  const {
    runId, tempDir, adapter, cloneResult, platform,
    filteredReadme, generatedChineseReadme, files, log,
  } = input;
  const emit = input.onEvent ?? (() => {});

  const targetRepo = `${cloneResult.meta.owner}/${cloneResult.meta.name}`;

  emit({ type: "step:start", step: "submit", message: "开始提交..." });

  const existingEn = detectEnglishReadme(files);
  const englishReadmeName = existingEn ? basename(existingEn.path) : "README.en.md";

  // 写中文 README（如有）
  if (generatedChineseReadme) {
    await writeFile(join(tempDir, "README.md"), generatedChineseReadme, "utf-8");
    log.info("中文 README.md 已写入临时目录");
  }

  // 写英文 README
  const targetPath = join(tempDir, englishReadmeName);
  await writeFile(targetPath, filteredReadme, "utf-8");

  let forkUrl: string | undefined;
  let forkOwner: string | undefined;
  let branchName = "";
  const originalBranch = defaultBranch(tempDir, log);

  const recoveryInfo: SubmitRecoveryInfo = {
    failedAt: "fork",
    remoteResources: {},
    recoveryCommands: [],
  };

  try {
    // Step 1: Fork
    emit({ type: "progress", message: "Fork 仓库..." });
    log.info("── Fork 仓库 ──");
    const forkResult = await adapter.forkRepo(cloneResult.meta.owner, cloneResult.meta.name, log);
    forkUrl = forkResult.forkUrl;
    forkOwner = forkResult.forkOwner;
    recoveryInfo.remoteResources.forkUrl = forkUrl;
    recoveryInfo.remoteResources.forkOwner = forkOwner;

    // Step 2: Add remote
    emit({ type: "progress", message: "添加 Fork Remote..." });
    log.info("── 添加 Fork Remote ──");
    addForkRemote(tempDir, forkResult.forkUrl, log);

    // Step 3: Create branch
    recoveryInfo.failedAt = "branch";
    emit({ type: "progress", message: "创建分支..." });
    log.info("── 创建分支 ──");
    createBranch(tempDir, "repopassport/en-readme", log);
    branchName = currentBranch(tempDir, log);
    recoveryInfo.remoteResources.branchName = branchName;

    // Step 4: Stage
    recoveryInfo.failedAt = "commit";
    emit({ type: "progress", message: "Stage 文件..." });
    log.info("── Stage 文件 ──");
    if (generatedChineseReadme) {
      stageFile(tempDir, "README.md", log);
    }
    stageFile(tempDir, englishReadmeName, log);

    // Step 5: Commit
    emit({ type: "progress", message: "提交..." });
    log.info("── Commit ──");
    const commitMsg = generatedChineseReadme
      ? "docs: add Chinese and English README"
      : "docs: add English README";
    commit(
      tempDir,
      commitMsg,
      "AI-assisted English README generation. Human-reviewed before submission.\n\n" +
        "Evidence extracted from:\n- package.json\n- Source files\n- Existing documentation\n\n" +
        `Generated by RepoPassport (run: ${runId})`,
      log,
    );

    // Step 6: Push
    recoveryInfo.failedAt = "push";
    emit({ type: "progress", message: "Push 到 Fork..." });
    log.info("── Push 到 Fork ──");
    pushBranch(tempDir, "repopassport-fork", branchName, log);
    recoveryInfo.remoteResources.remotePushed = true;

    // Step 7: Create Draft PR
    recoveryInfo.failedAt = "pr_create";
    emit({ type: "progress", message: "创建 Draft PR..." });
    log.info("── 创建 Draft PR ──");
    const prResult = await adapter.createDraftPr(
      {
        targetOwner: cloneResult.meta.owner,
        targetRepo: cloneResult.meta.name,
        baseBranch: cloneResult.meta.defaultBranch,
        headUser: forkOwner,
        headBranch: branchName,
        title: "docs: add English README",
        body:
          "## Summary\n\n" +
          "AI-assisted English README generation. Human-reviewed before submission.\n\n" +
          "## What Changed\n\n" +
          `- Added ${englishReadmeName} (English README)\n` +
          "- Original Chinese README.md preserved\n\n" +
          "Evidence extracted from:\n" +
          "- package.json\n- Source files\n- Existing documentation\n\n" +
          `Generated by RepoPassport (run: ${runId})`,
      },
      log,
    );

    // Step 8: Save PR record
    recoveryInfo.failedAt = "pr_record";
    const prRecordId = uuid();
    await savePrRecord(
      {
        id: prRecordId,
        runId,
        platform,
        prUrl: prResult.prUrl,
        targetRepo,
        forkUrl,
        branchName,
        createdAt: new Date().toISOString(),
        status: "open",
        lastCheckedAt: new Date().toISOString(),
      },
      log,
    );

    emit({
      type: "step:complete",
      step: "submit",
      message: `Draft PR 已创建: ${prResult.prUrl}`,
      data: { prUrl: prResult.prUrl },
    });

    return {
      success: true,
      prUrl: prResult.prUrl,
      prRecordId,
      partialFailure: false,
    };

  } catch (submitErr) {
    const msg = submitErr instanceof Error ? submitErr.message : String(submitErr);
    log.error(`提交失败: ${sanitizeForOutput(msg)}`);

    // Local cleanup only
    await rollbackLocal(tempDir, branchName, originalBranch, forkUrl, log);

    // Build recovery info
    recoveryInfo.recoveryCommands = buildRecoveryCommands(
      recoveryInfo,
      targetRepo,
      cloneResult.meta.defaultBranch,
      branchName,
      forkOwner,
    );

    const isPartialFailure =
      recoveryInfo.remoteResources.forkUrl !== undefined ||
      recoveryInfo.remoteResources.remotePushed === true;

    emit({
      type: "step:error",
      step: "submit",
      message: isPartialFailure ? "部分操作已执行" : "提交失败",
      data: { error: sanitizeForOutput(msg), recoveryInfo },
    });

    return {
      success: false,
      recoveryInfo,
      error: sanitizeForOutput(msg),
      partialFailure: isPartialFailure,
    };
  }
}

// ── 辅助函数 ──

function detectEnglishReadme(files: FileContent[]): FileContent | null {
  const patterns = [/README\.en\.md/i, /README_EN\.md/i, /README-en\.md/i];
  for (const f of files) {
    const name = f.path.split(/[/\\]/).pop() || "";
    if (patterns.some((p) => p.test(name))) {
      return f;
    }
  }
  return null;
}

async function rollbackLocal(
  cwd: string,
  branchName: string | undefined,
  originalBranch: string,
  forkUrl: string | undefined,
  log: Logger,
): Promise<void> {
  try {
    if (branchName) {
      try {
        execGit(cwd, `checkout ${originalBranch}`, log);
        execGit(cwd, `branch -D ${branchName}`, log);
      } catch {
        // 分支可能不存在
      }
    }
    if (forkUrl) {
      removeForkRemote(cwd, log);
    }
  } catch {
    log.verbose("本地回滚过程中出现可忽略的错误");
  }
  log.info("本地回滚完成（远端资源未被触碰）");
}

function buildRecoveryCommands(
  info: SubmitRecoveryInfo,
  targetRepo: string,
  baseBranch: string,
  branchName: string | undefined,
  forkOwner: string | undefined,
): string[] {
  const cmds: string[] = [];

  if (info.failedAt === "push" || info.failedAt === "pr_create" || info.failedAt === "pr_record") {
    if (info.remoteResources.remotePushed && branchName && forkOwner) {
      cmds.push(
        `# Push 已完成，手动创建 PR（以 GitHub 为例）：\n` +
        `# gh pr create --repo ${targetRepo} --base ${baseBranch} --head ${forkOwner}:${branchName} ` +
        `--title "docs: add English README" --draft`,
      );
    }
  }

  if (info.failedAt === "pr_create" || info.failedAt === "pr_record") {
    cmds.push(`# PR 可能已创建但本地记录失败，请在平台页面检查`);
  }

  if (info.failedAt === "fork" && info.remoteResources.forkUrl) {
    cmds.push(
      `# Fork 已创建但后续步骤失败，检查远程 Fork：\n` +
      `# ${info.remoteResources.forkUrl}`,
    );
  }

  return cmds;
}

function sanitizeForOutput(msg: string): string {
  let sanitized = msg;

  const apiKey = process.env["OPENAI_API_KEY"];
  if (apiKey && apiKey.length > 4) {
    sanitized = sanitized.replaceAll(apiKey, "***REDACTED***");
  }

  const giteeToken = process.env["GITEE_TOKEN"];
  if (giteeToken && giteeToken.length > 4) {
    sanitized = sanitized.replaceAll(giteeToken, "***REDACTED***");
  }

  sanitized = sanitized.replace(/sk-[a-zA-Z0-9]{20,}/g, "***REDACTED***");
  sanitized = sanitized.replace(/Bearer\s+[a-zA-Z0-9\-_+.]+/gi, "Bearer ***REDACTED***");

  return sanitized;
}
